# https://github.com/marketplace/actions/electron-builder-action

name: Build/release

on:
  push:
    branches:
      - 'main'
      - 'master'

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ windows-latest ]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 21

      - name: Build/release Electron app
        run: pnpm i && pnpm run release
        env:
          GITHUB_TOKEN: ${{ secrets.SEER2_NEXT_CLIENT_RELEASE_GH_TOKEN }}